path: '/content/gdrive/My Drive/' # finish with rest of path, dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

names:
  0: Tin can
